---
inherit_gem:
  eac_rails_gem_support: ".rubocop.yml"
Gemspec/DeprecatedAttributeAssignment:
  Exclude:
  - eac_users_support.gemspec
Gemspec/RequiredRubyVersion:
  Exclude:
  - eac_users_support.gemspec
Layout/MultilineMethodCallIndentation:
  Exclude:
  - config/initializers/menus.rb
Metrics/MethodLength:
  Exclude:
  - db/migrate/20200322051231_add_devise_invitable_to_eac_users_support_users.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - config/initializers/menus.rb
  - eac_users_support.gemspec
  - lib/tasks/eac_users_support.rake
  - spec/lib/eac_users_support/tasks/password_reset_spec.rb
  - spec/lib/rubocop_check_spec.rb
  - spec/spec_helper.rb
Style/StringConcatenation:
  Exclude:
  - app/controllers/eac_users_support/admin/users_controller.rb
