AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - '**/db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Exclude:
    - '**/db/migrate/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
